services:
  - type: web
    name: vk-bot-woleeria
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: VK_GROUP_TOKEN
        sync: false 